# Generated by Django 5.0 on 2024-03-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produts',
            new_name='Products',
        ),
    ]
