# Generated by Django 5.0 on 2024-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
