# Generated by Django 5.0 on 2024-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_organization_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='products',
            name='keywords',
        ),
        migrations.AddField(
            model_name='products',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='productApp.keyword'),
        ),
    ]
